[package]
name = "wreathctl"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
wreath-core = { path = "../wreath-core" }
toml.workspace = true

[target.'cfg(windows)'.dependencies]
wreath-windows = { path = "../wreath-windows" }
